name: Deploy React App

on:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Install dependencies 
       run : npm install

     - name: Build and Deploy
       run: |
            npm run build
          git config user.email "tamilmani793@gmail.com"
          git config user.name "Tamilmani"
          gh-pages -d build